### ISSUE TITLE
Hello, how can I get the Recipe1M dataset? The official link is no longer available for download.

### ISSUE THREAD

**Issue by jH144270429** [SanshruthR/RecipeNet#1]

**Comment by SanshruthR** [comment]
Hello,

When I received the Recipe1M dataset, I agreed to the following terms:

1. MIT CSAIL does not own the copyright to the recipes or images.
2. The data is for non-commercial research and educational purposes only.
3. The URLs for the data must not be distributed.
4. MIT CSAIL makes no guarantees about the data, including non-infringement or suitability for a particular purpose.
5. I accept full responsibility for my use of the data and must protect MIT CSAIL from any claims arising from my use of it.

If the official link is no longer available, try reaching out to the authors of the paper. You can find their contact information in the paper or on their institutional webpages. Explain your research or educational purpose and request access to the dataset directly.

**Comment by jH144270429** [comment]
Thank you very much for your reply, but I would like to ask how you applied for the dataset, because I have applied for it for more than 20 days using the email address provided on the official website, but have not received a reply.
